# version: "3"

services:
  app_server:
    build:
      # context: .
      # dockerfile: ./Dockerfile
      image: yuhwepo/sgroup-backend-v2
    tty: true
    container_name: app-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - example-network

  mysql:
    image: mysql:8.0
    container_name: app-sql
    command: --default-authentication-plugin=mysql_native_password
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_PASSWORD: nvmh2309
      MYSQL_DATABASE: nodejs
      MYSQL_USER: yuhwepo
      TZ: UTC
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data3:/var/lib/mysql
    networks:
      - example-network

networks:
  example-network:
    driver: bridge
